In [ ]:
using Pkg
Pkg.add("InvertedIndices")
rand(3,3,3)[Not(1), 1,1]

   Updating registry at `C:\Users\nickh\.julia\registries\General`


In [1]:
using StatsBase
using LinearAlgebra
using Distributions
include("FHMMs.jl")

Y = rand(5,4)

Main.FHMMs.fit_sv2!(Main.FHMMs.FHMM(5,3,2), Y)
#test.W

"γ"

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.542021  0.0507338  0.407246
 0.911619  0.0202221  0.0681593

[:, :, 2] =
 0.0141049  0.977909  0.0079864
 0.195217   0.574914  0.229869

[:, :, 3] =
 0.388302  0.306767  0.304931
 0.539337  0.357787  0.102876

[:, :, 4] =
 0.0355507  0.476464  0.487986
 0.198595   0.292964  0.508441

"ξ"

2×3×3×3 Array{Float64,4}:
[:, :, 1, 1] =
 0.00649174  0.0019861  0.00562706
 0.137247    0.0204414  0.0375283

[:, :, 2, 1] =
 0.45008   0.137699   0.39013
 0.404193  0.0601998  0.110521

[:, :, 3, 1] =
 0.00367572  0.00112456  0.00318612
 0.16161     0.0240699   0.0441899

[:, :, 1, 2] =
 0.0385259  0.320787  0.0289897
 0.141885   0.243488  0.153963

[:, :, 2, 2] =
 0.0304362  0.253428  0.0229024
 0.0941241  0.161526  0.102137

[:, :, 3, 2] =
 0.0302541  0.251911   0.0227654
 0.0270638  0.0464442  0.0293678

[:, :, 1, 3] =
 0.0128111  0.0113869  0.0113528
 0.0882162  0.0718507  0.0385279

[:, :, 2, 3] =
 0.171699  0.152611  0.152154
 0.130135  0.105993  0.0568358

[:, :, 3, 3] =
 0.175851  0.156302  0.155833
 0.225851  0.183952  0.0986388

"C⁻¹"

5×5 Array{Float64,2}:
  0.244646   0.0202715    0.142736   -0.0359695   -0.0190717
  0.0202715  0.469594     0.371658    0.00628677   0.00212293
  0.142736   0.371658     0.69462    -0.0715104   -0.0628832
 -0.0359695  0.00628677  -0.0715104   0.14337     -0.0239619
 -0.0190717  0.00212293  -0.0628832  -0.0239619    0.282797

"Δ"

3×1×2 Array{Float64,3}:
[:, :, 1] =
 1.0439961079568723
 0.3595982285009036
 0.4466692261536687

[:, :, 2] =
 1.0751895292176845
 0.3666132987457177
 0.5361998692516124

"Ỹ"

5×2×4 Array{Float64,3}:
[:, :, 1] =
 -0.118361   -0.114882
 -0.104985    0.0858128
  0.0657767  -0.423337
  0.239893   -0.0653341
  0.0624169   0.522211

[:, :, 2] =
 -0.417858  -0.402277
 -0.326121  -0.0794266
  0.317326   0.105998
  0.629649   0.21349
 -0.105709  -0.550634

[:, :, 3] =
  0.348909    0.404792
 -0.217617    0.00532211
  0.0607457  -0.233567
 -0.140592   -0.507071
 -0.173747   -0.0541213

[:, :, 4] =
  0.382811   0.196487
 -0.168059  -0.0908822
  0.122039  -0.0224227
 -0.174331  -0.408118
 -0.213008  -0.0808368

"h pre exp"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 -0.567518  -0.673282  -0.554064  -0.491307
 -0.211182  -0.246109  -0.184303  -0.138106
 -0.237186  -0.290495  -0.257667  -0.223737

[:, :, 2] =
 -0.829295  -0.626256  -0.607749  -0.550397
 -0.146532  -0.319517  -0.235599  -0.232778
 -0.488945  -0.335006  -0.275775  -0.256149

"h"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 0.566931  0.510032  0.57461   0.611826
 0.809627  0.781837  0.831684  0.871007
 0.788845  0.747893  0.772852  0.799525

[:, :, 2] =
 0.436357  0.534589  0.544575  0.576721
 0.863698  0.7265    0.790097  0.792329
 0.613273  0.715334  0.758984  0.774027

"pi"

3×2 Array{Float64,2}:
 0.542021   0.911619
 0.0507338  0.0202221
 0.407246   0.0681593

"W"

5×3×2 Array{Float64,3}:
[:, :, 1] =
  1.09988     -0.795371  -1.10004
  0.188807     0.381932   0.172825
 -0.00628198   0.340964   0.395437
 -0.618783     1.19571    1.39398
  0.237686     0.737585   0.0588819

[:, :, 2] =
  2.19859     1.54686    0.14348
  0.0626373   0.179343   0.0964054
 -0.0696114   0.0908848  0.208687
 -1.48662    -0.962006   0.104105
 -0.327589    0.275486   0.162057

"P"

3×3×2 Array{Float64,3}:
[:, :, 1] =
 0.0612315  0.4884    0.291296
 0.353823   0.40717   0.568396
 0.0486744  0.423231  0.252422

[:, :, 2] =
 0.223153  0.659499  1.03397
 0.203977  0.34391   0.634729
 0.13973   0.282807  0.42952

"C"

5×5 Array{Float64,2}:
 -0.206686  -0.207655  -0.213451  -0.248979   -0.222567
 -0.353904  -0.242407  -0.242383  -0.197494   -0.260321
 -0.268688  -0.177478  -0.142266  -0.0868459  -0.252901
 -0.309019  -0.14324   -0.124714  -0.013834   -0.181149
 -0.350506  -0.223079  -0.230464  -0.175296   -0.221209

"γ"

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.397882  0.102392   0.499726
 0.891766  0.0484255  0.0598082

[:, :, 2] =
 0.170362  0.513261  0.316377
 0.337727  0.388224  0.274049

[:, :, 3] =
 0.170358  0.564191  0.265451
 0.316219  0.410714  0.273067

[:, :, 4] =
 0.268068  0.381626  0.350307
 0.269109  0.369716  0.361175

"ξ"

2×3×3×3 Array{Float64,4}:
[:, :, 1, 1] =
 0.0142399  0.010999    0.0118341
 0.114164   0.00458183  0.0075117

[:, :, 2, 1] =
 0.342194  0.0381336   0.31001
 0.387844  0.00888014  0.0174766

[:, :, 3, 1] =
 0.125805  0.0328133  0.11397
 0.429236  0.0115694  0.0187368

[:, :, 1, 2] =
 0.00695559  0.0616118  0.00810779
 0.0467189   0.0580344  0.0391443

[:, :, 2, 2] =
 0.183738  0.23481   0.233476
 0.179331  0.127087  0.102901

[:, :, 3, 2] =
 0.0515604  0.154224  0.0655165
 0.18693    0.155946  0.103907

[:, :, 1, 3] =
 0.01254    0.10488    0.0134075
 0.0355679  0.0471692  0.0310399

[:, :, 2, 3] =
 0.142394  0.171821  0.165965
 0.144414  0.10926   0.0863101

[:, :, 3, 3] =
 0.0779582  0.220173  0.0908609
 0.221185   0.196996  0.128057

"C⁻¹"

5×5 Array{Float64,2}:
 -2.33349e15   5.58846e15  -1.57133e14  -1.54753e15  -2.78181e15
  5.9113e15   -1.41570e16   3.98056e14   3.92029e15   7.04702e15
  1.51359e15  -3.62489e15   1.01922e14   1.00379e15   1.80439e15
 -2.93986e15   7.04065e15  -1.97964e14  -1.94967e15  -3.50468e15
 -1.51111e15   3.61896e15  -1.01756e14  -1.00215e15  -1.80144e15

"Δ"

3×1×2 Array{Float64,3}:
[:, :, 1] =
 16.52237885554584
 18.62971005213181
 15.344800218830319

[:, :, 2] =
 93.32149307588575
 11.140484014874682
 -1.3540886214437085

"Ỹ"

5×2×4 Array{Float64,3}:
[:, :, 1] =
  0.693001  -1.54465
  0.339561   0.469847
  0.147292   0.42251
 -0.162219   1.7767
  0.721307   1.18993

[:, :, 2] =
  0.662722   -1.28853
  0.0229596   0.188634
  0.16281     0.392886
 -0.199867    1.59646
 -0.381656    0.0153133

[:, :, 3] =
  1.48711    -0.436003
  0.125813    0.299546
  0.0307705   0.254738
 -0.921516    0.85449
  0.0193719   0.437824

[:, :, 4] =
  1.22296    -0.386459
  0.0628805   0.201809
  0.119003    0.295722
 -0.751155    0.745734
 -0.061981    0.231618

"h pre exp"

3×4×2 Array{Float64,3}:
[:, :, 1] =
  -6.84885   15.657    18.2253   14.2584
 -12.1193   -27.8693  -33.7628  -30.7072
 -11.8352   -26.5893  -34.2103  -30.0252

[:, :, 2] =
 -131.536   -69.1527   -62.9864   -55.4319
  -25.2548  -21.605    -14.2349   -12.8138
   27.9351   -1.15243    1.73222   -0.567705

"h"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 0.00106067  6.30598e6    8.22529e7    1.55719e6
 5.45343e-6  7.87972e-13  2.17262e-15  4.61361e-14
 7.24512e-6  2.83395e-12  1.38887e-15  9.12517e-14

[:, :, 2] =
 7.49006e-58  9.27649e-31  4.41951e-28  8.43822e-25
 1.07645e-11  4.14047e-10  6.57441e-7   2.723e-6
 1.35542e12   0.315868     5.65321      0.566825

"pi"

3×2 Array{Float64,2}:
 0.397882  0.891766
 0.102392  0.0484255
 0.499726  0.0598082

"W"

5×3×2 Array{Float64,3}:
[:, :, 1] =
  15.6166    1.53961     2.2793
   2.06757   0.679373    0.587568
  -2.09688  -0.0926139  -0.198829
 -13.5516   -0.786362   -1.42381
   8.23684   1.71722     1.34962

[:, :, 2] =
  0.142335   -14.8285    1.38539
  0.0529222   -1.90527   0.0175738
  0.23755      2.58973   0.149083
  0.244046    13.4058   -1.0273
 -0.249621    -8.04152   0.0773338

"P"

3×3×2 Array{Float64,3}:
[:, :, 1] =
 0.0456748  0.566453  0.236071
 0.240307   0.376969  0.376504
 0.045152   0.60131   0.249962

[:, :, 2] =
 0.127094   0.839769  1.37966
 0.0710258  0.2894    0.600588
 0.0502654  0.243919  0.413068

"C"

5×5 Array{Float64,2}:
 -0.156621   -0.224565   -0.200213    -0.272961    -0.306116
  0.0213968   0.0253803   0.00969271   0.00962942   0.057218
  0.0225024   0.0311142   0.0283725    0.0373574    0.0427069
  0.138879    0.200525    0.178166     0.24423      0.273279
  0.0779088   0.0871092   0.0288893    0.0214527    0.207654

"γ"

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.999906      3.57883e-5   5.79252e-5
 1.52077e-137  7.42521e-47  1.0

[:, :, 2] =
 1.0          8.21496e-38  1.99655e-37
 2.88077e-59  2.4983e-18   1.0

[:, :, 3] =
 1.0          8.17444e-46  3.01325e-46
 2.02772e-56  1.83772e-14  1.0

[:, :, 4] =
 1.0          2.96277e-20  5.86001e-20
 1.48867e-24  4.80393e-6   0.999995

"ξ"

2×3×3×3 Array{Float64,4}:
[:, :, 1, 1] =
 0.984793      0.00685546   0.00835195
 7.30317e-128  3.18519e-83  3.50555e-60

[:, :, 2, 1] =
 1.00332e-36  8.83451e-40  9.13723e-39
 4.18488e-86  1.12553e-41  1.47526e-18

[:, :, 3, 1] =
 1.01623e-36  2.14447e-39  9.23134e-39
 2.75203e-68  9.34951e-24  1.0

[:, :, 1, 2] =
 1.0          6.57427e-19  4.44263e-19
 1.83227e-86  4.57033e-66  2.46749e-57

[:, :, 2, 2] =
 1.01378e-44  8.43035e-64  4.83637e-63
 1.09722e-43  1.68772e-23  1.08518e-14

[:, :, 3, 2] =
 1.55741e-45  3.10375e-64  7.41093e-64
 9.80912e-30  1.9059e-9    1.0

[:, :, 1, 3] =
 1.0          1.3897e-22   1.66921e-23
 3.58082e-53  2.97685e-32  1.81154e-25

[:, :, 2, 3] =
 3.6744e-19   6.45893e-42  6.58612e-42
 7.63509e-34  3.91414e-13  2.83675e-6

[:, :, 3, 3] =
 3.02876e-19  1.27592e-41  5.4151e-42
 2.61113e-28  1.69089e-7   0.999997

"C⁻¹"

5×5 Array{Float64,2}:
 -1.757e16     4.4509e16    1.13965e16  -2.21356e16  -1.13779e16
  4.4509e16   -1.12752e17  -2.88702e16   5.60749e16   2.8823e16
  1.13965e16  -2.88702e16  -7.39221e15   1.4358e16    7.38013e15
 -2.21356e16   5.60749e16   1.4358e16   -2.78876e16  -1.43345e16
 -1.13779e16   2.8823e16    7.38013e15  -1.43345e16  -7.36807e15

"Δ"

3×1×2 Array{Float64,3}:
[:, :, 1] =
 -15978.484053129938
  -2277.2767776153687
  -4358.998081833226

[:, :, 2] =
  -250.67714278712523
 25790.457656804778
 -1609.5245626336073

"Ỹ"

5×2×4 Array{Float64,3}:
[:, :, 1] =
 -15.1158   -0.885931
  -1.52728   0.522582
   2.47402   0.228232
  13.961     1.43792
  -7.31538   0.843492

[:, :, 2] =
 -15.5227   -1.29155
  -1.76173   0.28826
   2.55873   0.312768
  14.301     1.77675
  -8.1808   -0.0212942

[:, :, 3] =
 -14.6828   -0.451664
  -1.64823   0.401763
   2.42392   0.177956
  13.5693    1.04501
  -7.74521   0.414299

[:, :, 4] =
 -14.7877   -0.556395
  -1.74778   0.302226
   2.48285   0.236869
  13.5792    1.05484
  -7.93299   0.226548

"h pre exp"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 -25257.8   -25433.9  -25430.2   -23625.5
  -1707.16   -1731.8   -1726.48   -1588.71
  -3090.82   -3126.4   -3118.19   -2855.54

[:, :, 2] =
  -195.753   -192.589   -196.386   -174.265
 15680.1    15849.7    15860.6    14123.9
 -1693.79   -1694.49   -1704.05   -1533.49

"h"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
  9.67176e-86   2.28996e-84   5.13606e-86   2.07849e-76
 Inf           Inf           Inf           Inf
  0.0           0.0           0.0           0.0

"pi"

3×2 Array{Float64,2}:
 0.999906    1.52077e-137
 3.57883e-5  7.42521e-47
 5.79252e-5  1.0

"W"

5×3×2 Array{Float64,3}:
[:, :, 1] =
  13462.7    -2.02592e-10    9628.54
  -2553.37    2.47692e-11    -476.405
   -289.807   5.72466e-12    -341.88
 -15251.9     2.28675e-10  -10824.7
  -1395.73   -2.94115e-11    3984.7

[:, :, 2] =
  52137.5    15584.3    -13462.2
  -6354.57    -771.087    2553.74
  -1475.23    -553.351     290.202
 -58848.9   -17520.4     15252.3
   7642.38    6449.45     1396.0

"P"

3×3×2 Array{Float64,3}:
[:, :, 1] =
 0.994962    1.0267e-14   5.22874e-15
 0.00228523  2.4866e-35   3.72416e-35
 0.00278407  2.55498e-34  1.5946e-34

[:, :, 2] =
 1763.43         4.15409e-20  9.03075e-29
    1.46599e24  21.296        5.69984e-8
    8.92122e30   1.54342e8    0.999999

"C"

5×5 Array{Float64,2}:
 -9.55948   -6.49857   -6.38307   -5.04461   -7.239
 -0.989327  -0.660426  -0.657702  -0.511518  -0.7194
  1.36148    0.923253   0.908708   0.716318   1.02584
  8.66534    5.89396    5.78648    4.57599    6.56872
 -4.60284   -3.09018   -3.06334   -2.39607   -3.38747

"γ"

2×3×4 Array{Float64,3}:
[:, :, 1] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 2] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 3] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 4] =
 NaN  NaN  NaN
 NaN  NaN  NaN

"ξ"

2×3×3×3 Array{Float64,4}:
[:, :, 1, 1] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 2, 1] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 3, 1] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 1, 2] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 2, 2] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 3, 2] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 1, 3] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 2, 3] =
 NaN  NaN  NaN
 NaN  NaN  NaN

[:, :, 3, 3] =
 NaN  NaN  NaN
 NaN  NaN  NaN

"C⁻¹"

5×5 Array{Float64,2}:
  4.22355e14  -1.06993e15  -2.73955e14   5.32105e14   2.73507e14
 -1.06993e15   2.71039e15   6.93996e14  -1.34795e15  -6.92861e14
 -2.73955e14   6.93996e14   1.77697e14  -3.45143e14  -1.77407e14
  5.32105e14  -1.34795e15  -3.45143e14   6.70376e14   3.44579e14
  2.73507e14  -6.92861e14  -1.77407e14   3.44579e14   1.77117e14

"Δ"

3×1×2 Array{Float64,3}:
[:, :, 1] =
 1.0110855235514666e10
 2.5182987408827526e-18
 6.316233068586361e9

[:, :, 2] =
 1.665186487493188e11
 1.655337398953288e10
 1.050763121000628e10

"Ỹ"

5×2×4 Array{Float64,3}:
[:, :, 1] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

[:, :, 2] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

[:, :, 3] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

[:, :, 4] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

"h pre exp"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN

[:, :, 2] =
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN

"h"

3×4×2 Array{Float64,3}:
[:, :, 1] =
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN

[:, :, 2] =
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN

LoadError: LAPACKException(5)

In [8]:


function generate(model::Main.FHMMs.FHMM, timesteps::Int)
    X = zeros(size(model.W)[1], timesteps)
    # choose initial states based on π
    states = zeros(Int64, model.M, timesteps)
    for m=1:model.M
        idx = sample(weights(model.π[:,m]))
        states[m,1] = Int64(idx)
    end
    for t=1:timesteps    
        mu = zeros(model.D)
        for m=1:model.M
            mu += model.W[:,states[m,t],m]
        end
        n = MvNormal(mu, model.C)
        X[:,t] = rand(n)
        if t < timesteps
            for m=1:model.M
                nsp = model.P[states[m,t],:,m]
                #display(nsp)
                smpl = sample(weights(nsp))
                states[m,t+1] = smpl
            end
        end
    end
    return X,states
end

generate (generic function with 3 methods)

In [ ]:
function sample_states(model::Main.FHMMs.FHMM, timesteps::Int, iter=1000)
    # we need to sample theta, KxMxT
    # θ[1,1,2] represents the probabilities of chain (1) being in state (1) at time 2, 
    # θ[3,1,2] represents the probabilities of chain (1) being in state (3) at time 2, etc
    # this is unconditional wrt the observation
    theta_sampled = zeros(model.K,model.M, timesteps)
    for i=1:iter
        theta_iter = zeros(model.K,model.M,timesteps)
        for m=1:model.M
            s = sample(weights(model.π[:,m]))
            theta_iter[s, m,1] += 1
        end
        for t=2:timesteps
            for m=1:model_actual.M
                lastState = findfirst((t) -> t == 1, theta_iter[:,m,t-1])
                s = sample(weights(model.P[lastState,:,m]))
                theta_iter[s,m,t] += 1
            end
        end
        theta_sampled .+= theta_iter
    end
    theta_sampled ./= iter
    return theta_sampled
end


In [ ]:
function get_state_combinations(M::Int, K::Int)
    state_combinations = []
    m = 1
    stack = []
    while(true)
        if(m == M)
            if(size(stack)[1] != M - 1)
                break
            end
            for s=1:K
                push!(stack, s)
                push!(state_combinations, copy(stack))
                pop!(stack)
            end
            stack[end] +=1
            while(stack[end] > K)
                pop!(stack)
                if(size(stack)[1] == 0)
                    break
                end
                stack[end] +=1
                m -= 1
            end
        else
            push!(stack, 1)
            m += 1
        end
    end
    return state_combinations
end

In [ ]:
# we want to calculate 
# P(Mt=St|Yt)
# = P(Yt|Mt=St).P(Mt=St|Mt-1=St-1) / P(Yt)
# This decoding is specific to the completely factorized VI model which uses a simplified P(Mt|Yt) that assumes 
# no dependence between timesteps. Viterbi decoding is therefore not required, since we don't need to find the max sequence,
# we just take the max P at each timestep.
# even though each chain is independent but the observation is conditional on *all* chains 
# this is because Yt is a sum of M1,M2,M3...
# i.e. P(Yt|M1t=S1t,M2t=.., M3t=..) != P(Yt|M1t=S1t)
# but we have θ, which is an estimation of P(M1t=S1t), P(M1t=S2t)...P(Mmt=Sst)
# so we need to find all configurations of M/S at this t
# cross product of (M1xS)x(M2xS)x..x(MkxS)
# if we are using the variational inference model, θ is KxMxT
# θ[1,1,2] represents p(chain (1) in state (1) at time 2) 
# θ[3,1,2] represents p(chain (1) in state (3) at time 2), etc
# this is unconditional wrt the observation
# i.e. P(Mt=St|M(t-1)=S(t-1))
# therefore P(Mt=St) is the product over dim(1) at T
function decode(model::Main.FHMMs.FHMM, X::Array{Float64,2}, θ::Array{Float64,3})
    
    D=size(X)[1]
    timesteps=size(X)[2]
    
    states = zeros(model.M,timesteps)
    for t=1:timesteps
        pmax = -1
        mmax = []
        stack = []
        m = 1
        M = model.M
        K = model.K
        while(true)
            if(m == M)
                if(size(stack)[1] != M - 1)
                    break
                end
                for s=1:K
                    push!(stack, s)
                    mu = zeros(D)
                    for i=1:M
                        mu += model.W[:, stack[i], i]
                    end
                    
                    p_yt_given_mt_in_s = pdf(MvNormal(mu, Array{Float64,2}(Hermitian(Symmetric(model.C)))), X[:,t])
                    p_mt_in_s = reduce(*, θ[stack,:,t])
                    unnormalized = p_yt_given_mt_in_s * p_mt_in_s
                    if unnormalized > pmax
                        pmax = unnormalized
                        mmax = copy(stack)
                    end
                    pop!(stack)
                end
                stack[end] +=1
                while(stack[end] > K)
                    pop!(stack)
                    if(size(stack)[1] == 0)
                        break
                    end
                    stack[end] +=1
                    m -= 1
                end
            else
                push!(stack, 1)
                m += 1
            end
        end
        states[:,t] = mmax
    end
    return states
end

In [ ]:
function decode_full(model::Main.FHMMs.FHMM, X::Array{Float64,2})
    D=size(X)[1]
    timesteps=size(X)[2]
    state_combinations = get_state_combinations(model.M, model.K)
    state_probabilities = zeros(size(state_combinations)[1],timesteps)
    
    M = model.M
    K = model.K
    logP = log.(model.P)
    for t=1:timesteps
        for s_index=1:size(state_combinations)[1]
            state = state_combinations[s_index]
            mu = zeros(D)
            for i=1:model.M
                mu += model.W[:, state[i], i]
            end
            p_yt_given_mt_in_s = pdf(MvNormal(mu, Array{Float64,2}(Hermitian(Symmetric(model.C)))), X[:,t])
                   
            if(t == 1)
               p_mt_in_s = reduce(*, model.π[[CartesianIndex(state[i], i)  for i=1:model.M]])
            else
                # calculate the probability that chain M is in state K, P(Mt)
                # this is P(Mt|Mt-1, Yt), so P(Mt-1|Yt) * P(Mt|Mt-1)
                # P(Mt-1|Yt) is sum over K
                p_mt_in_s = 0
                for sc_last_index=1:size(state_combinations)[1]
                    sc_last = state_combinations[sc_last_index]
                    for m_last=1:M
                        for m_this=1:M
                            p_mt_in_s += exp(
                                state_probabilities[sc_last_index,t-1] + 
                                logP[sc_last[m_this], state[m_this], m_this])
                        end
                    end
                end
            end
            state_probabilities[s_index,t] = log(p_yt_given_mt_in_s) +  log(p_mt_in_s)
         end
    end
    max_probs = zeros(M, timesteps)
    i = 1
    for p in argmax(state_probabilities, dims=1)
        max_probs[:, p[2]] = state_combinations[p[1]]
        i += 1
    end
    return max_probs
end

#X, actual = generate(model_actual, 2)
#decoded = decode_full(model_actual,X)
#actual .== decoded

In [ ]:
# setup our known model
# 
D=15
K=3
M=2
#T=5
W=cat( [ 1.0 49.0; -1.0 -49.0 ],[ 1.0 49.0; -1.0 -49.0 ], [ 1.0 49.0; -1.0 -49.0 ], dims=3)
π = [ 0.35 0.25 0.95; 0.65 0.75 0.05; ]
P = cat([ 0.3 0.7 ; 0.2 0.8 ; ],
    [ 0.5 0.5 ; 0.4 0.6 ;  ],
    [ 0.75 0.25 ; 0.89 0.11 ; ], dims=3)
W = rand(D,K,M)
π = rand(K,M)
π ./= sum(π,dims=(1))
P = rand(K, K, M)
P ./= sum(P, dims=2)
#C = rand(D,D)
C = Array{Float64}(Diagonal([0.1 for x in 1:D]))
model_actual = Main.FHMMs.FHMM(D,K,M,
    W, π, P, C)

X, actual = generate(model_actual, 4)



In [ ]:
model_learn = Main.FHMMs.FHMM(D,K,M)
result = Main.FHMMs.fit_sv!(model_learn,X,maxiter=5000,verbose=true)    

In [ ]:
result.γ

In [ ]:
actual

In [ ]:
timesteps=10
num_observations = 100

theta_sampled = sample_states(model_actual, timesteps, 1000)
j = 0
for i in 1:num_observations
    X,actual_states = generate(model_actual, timesteps)
    estimated_states = decode(model_actual,X, theta_sampled)
    j += sum(actual_states .== estimated_states)
end
j / (num_observations * timesteps * model_actual.M)

In [ ]:
j = 0
for i in 1:num_observations
    X,actual_states = generate(model_actual, timesteps)
    estimated_states = decode_full(model_actual,X)
    j += sum(actual_states .== estimated_states)
end
j / (num_observations * timesteps * model_actual.M)

In [ ]:
model_learn = Main.FHMMs.FHMM(D,K,M)
j = 0
num_observations = 50
for i=1:num_observations
    X,actual_states = generate(model_actual, timesteps)
    
    result = Main.FHMMs.fit!(model_learn,X,maxiter=100)    
    
    estimated_states = decode_full(model_learn,X)
    j += sum(actual_states .== estimated_states)
end
j / (num_observations * timesteps * model_actual.M)

In [ ]:
timesteps=10
model_learn = Main.FHMMs.FHMM(D,K,M)
j = 0
num_observations = 100
for i=1:num_observations
    X,actual_states = generate(model_actual, timesteps)
    result = Main.FHMMs.fit!(model_learn,X,maxiter=100,fzero=true)    
    for i in 1:D
        model_learn.C[i, i] += 0.0001
    end
    #println(cholesky(Hermitian(Symmetric(model_learn.C))))
    estimated_states = decode(model_learn,X, result.θ)
    j += sum(actual_states .== estimated_states)
    println(j / (i * timesteps * model_actual.M))
end
j / (num_observations * timesteps * model_actual.M)